<script>
    let arregloDatapaciente = {
        area: "",
        cargo: "",
        fecha_ingreso: "",
        apellidos: "",
        nombres: "",
        genero: "",
        edad: "",
        religion: "",
        tipo_sangre: "",
        lateralidad: "",
        orientacion_sexual: "",
        identidad_genero: "",
        actividad_relevante: "",
        tipo_evaluacion: "",
        puesto_trabajo: "",
        puesto_trabajo_id: "",
        fecha_salida: "",
        fecha_reingreso: "",
        total_dias: "",
        factores_riesgo: "",
        tiempo_meses: "",
        causa_salida: "",
        primer_nombre: "",
        segundo_nombre: "",
        primer_apellido: "",
        segundo_apellido: "",
        cargo: "",
        motivo_consulta: "",
    };
</script>
